// T016 — Synthetic fixture workspaces with Claude Code-shaped JSONL transcripts.
//
// Layout produced (all content is deterministic — same bytes on every run):
//
//   tests/fixtures/ws-<name>/                          nine fixture workspaces
//   tests/fixtures/claude/projects/<encoded-ws>/       transcripts, one <session-id>.jsonl
//   tests/fixtures/growth/<ws-name>.base.jsonl         pristine copy for replay reset
//   tests/fixtures/growth/<ws-name>.turns.jsonl        turns replayed by append-turns.sh
//
// <encoded-ws> is the workspace's absolute path with "/" replaced by "-", exactly the
// way Claude Code encodes project directories under ~/.claude/projects. Because the
// encoding embeds the machine-specific absolute path, fixtures are (re)generated by
// this script rather than committed under a hard-coded encoded name. Tests call
// `generateFixtures()` in their setup; `npx tsx scripts/fixtures/generate-fixtures.ts`
// does the same from the shell.
//
// Fixture percentages assume the 200k context window of the known model
// `claude-sonnet-4-5` (the latest assistant entry's message.usage total is the
// context footprint):
//
//   ws-green      50,000 tokens ≈ 25%   exact
//   ws-yellow     90,400 tokens ≈ 45.2% exact (+ malformed lines that must be skipped,
//                 + three older sessions: unknown model, missing usage, [1m] window)
//   ws-orange    136,000 tokens ≈ 68%   exact
//   ws-red       160,000 tokens ≈ 80%   exact (task/question phrases for handoff)
//   ws-growing    70,000 tokens ≈ 35%   replayable to 136,000 ≈ 68% (multi-band jump)
//   ws-empty      zero-byte transcript  → reading unavailable, never a fake zone
//   ws-decisions  50,000 tokens ≈ 25%   decision/conclusion phrases, replayable to 68%
//   ws-no-matches 30,000 tokens ≈ 15%   deliberately bland: NO heuristic phrases —
//                 keep it free of decision/conclusion/constraint/result/task/question
//                 trigger phrases and question marks
//   ws-bad-config 90,000 tokens ≈ 45%   workspace has an invalid baton.config.json
//                 (orange 60 < yellow 65 → falls back to defaults with named error)
import { mkdirSync, rmSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

/** Encode a workspace path the way Claude Code does: absolute path, "/" → "-". */
export function encodeWorkspacePathForFixtures(absoluteWorkspace: string): string {
  return absoluteWorkspace.replaceAll('/', '-');
}

/** Repository root (this file lives at scripts/fixtures/). */
export function fixtureRepoRoot(): string {
  return resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
}

/** Session ids (transcript file stems), one per fixture transcript. */
export const SESSION_IDS = {
  green: '11111111-1111-4111-8111-111111111111',
  yellow: '22222222-2222-4222-8222-222222222222',
  yellowUnknownModel: '22222222-2222-4222-8222-aaaaaaaaaaaa',
  yellowNoUsage: '22222222-2222-4222-8222-bbbbbbbbbbbb',
  yellowBigWindow: '22222222-2222-4222-8222-cccccccccccc',
  orange: '33333333-3333-4333-8333-333333333333',
  red: '44444444-4444-4444-8444-444444444444',
  growing: '55555555-5555-4555-8555-555555555555',
  empty: '66666666-6666-4666-8666-666666666666',
  decisions: '77777777-7777-4777-8777-777777777777',
  noMatches: '88888888-8888-4888-8888-888888888888',
  badConfig: '99999999-9999-4999-8999-999999999999',
} as const;

/** Model ids used across fixtures. */
export const MODELS = {
  known: 'claude-sonnet-4-5',
  bigWindow: 'claude-sonnet-4-5[1m]',
  unknown: 'experimental-orion-1',
} as const;

interface Usage {
  input_tokens: number;
  cache_creation_input_tokens: number;
  cache_read_input_tokens: number;
  output_tokens: number;
}

function usage(
  input: number,
  cacheCreation: number,
  cacheRead: number,
  output: number,
): Usage {
  return {
    input_tokens: input,
    cache_creation_input_tokens: cacheCreation,
    cache_read_input_tokens: cacheRead,
    output_tokens: output,
  };
}

let uuidCounter = 0;
function nextUuid(): string {
  uuidCounter += 1;
  return `00000000-0000-4000-8000-${String(uuidCounter).padStart(12, '0')}`;
}

function summaryLine(text: string): string {
  return JSON.stringify({ type: 'summary', summary: text, leafUuid: nextUuid() });
}

function userLine(sessionId: string, cwd: string, timestamp: string, text: string): string {
  return JSON.stringify({
    type: 'user',
    uuid: nextUuid(),
    parentUuid: null,
    sessionId,
    timestamp,
    cwd,
    version: '2.0.0',
    gitBranch: 'main',
    message: { role: 'user', content: [{ type: 'text', text }] },
  });
}

function assistantLine(
  sessionId: string,
  cwd: string,
  timestamp: string,
  text: string,
  model: string,
  usageBlock: Usage | null,
): string {
  const message: Record<string, unknown> = {
    id: `msg_fixture_${String(uuidCounter).padStart(4, '0')}`,
    type: 'message',
    role: 'assistant',
    model,
    content: [{ type: 'text', text }],
    stop_reason: 'end_turn',
    stop_sequence: null,
  };
  if (usageBlock !== null) {
    message['usage'] = { ...usageBlock, service_tier: 'standard' };
  }
  return JSON.stringify({
    type: 'assistant',
    uuid: nextUuid(),
    parentUuid: null,
    sessionId,
    timestamp,
    cwd,
    version: '2.0.0',
    gitBranch: 'main',
    message,
  });
}

interface TranscriptSpec {
  workspaceName: string;
  sessionId: string;
  /** null → zero-byte transcript file. */
  lines: ((cwd: string) => string[]) | null;
}

function buildTranscripts(): TranscriptSpec[] {
  return [
    {
      workspaceName: 'ws-green',
      sessionId: SESSION_IDS.green,
      lines: (cwd) => [
        summaryLine('Early exploration of the monitor CLI'),
        userLine(
          SESSION_IDS.green,
          cwd,
          '2026-07-02T18:00:00.000Z',
          'Give me an overview of the monitor architecture layers.',
        ),
        assistantLine(
          SESSION_IDS.green,
          cwd,
          '2026-07-02T18:00:10.000Z',
          'The core library holds zone math and schemas, adapters read session data, and the CLI stays a thin presentation layer.',
          MODELS.known,
          usage(1200, 1800, 27_500, 300),
        ),
        userLine(
          SESSION_IDS.green,
          cwd,
          '2026-07-02T18:00:15.000Z',
          'Where do the zone thresholds live?',
        ),
        assistantLine(
          SESSION_IDS.green,
          cwd,
          '2026-07-02T18:00:20.000Z',
          'Thresholds come from baton.config.json with 40/60/75 defaults defined once in the config schema.',
          MODELS.known,
          usage(1800, 2700, 45_000, 500), // total 50,000 → 25.0% of 200k
        ),
      ],
    },
    {
      workspaceName: 'ws-yellow',
      sessionId: SESSION_IDS.yellow,
      lines: (cwd) => [
        summaryLine('Reader implementation session'),
        userLine(
          SESSION_IDS.yellow,
          cwd,
          '2026-07-02T18:10:00.000Z',
          'Walk through the transcript reader flow end to end.',
        ),
        assistantLine(
          SESSION_IDS.yellow,
          cwd,
          '2026-07-02T18:10:05.000Z',
          'The reader tail-parses the JSONL transcript, extracts the latest usage block, and classifies the percentage into a zone.',
          MODELS.known,
          usage(2400, 3100, 54_000, 500), // earlier, smaller usage — must NOT win
        ),
        // Malformed lines a tolerant reader must skip (T017/T019):
        'this line is not JSON at all',
        '{"type":"assistant","message":',
        '42',
        userLine(
          SESSION_IDS.yellow,
          cwd,
          '2026-07-02T18:10:10.000Z',
          'Now include the cache accounting fields in the total.',
        ),
        assistantLine(
          SESSION_IDS.yellow,
          cwd,
          '2026-07-02T18:10:15.000Z',
          'The context footprint sums input, cache reads, cache creation, and output tokens from the latest assistant usage block.',
          MODELS.known,
          usage(3400, 4200, 82_000, 800), // total 90,400 → 45.2% of 200k
        ),
      ],
    },
    {
      // Older session in ws-yellow: unknown model id → conservative 200k, estimated.
      workspaceName: 'ws-yellow',
      sessionId: SESSION_IDS.yellowUnknownModel,
      lines: (cwd) => [
        userLine(
          SESSION_IDS.yellowUnknownModel,
          cwd,
          '2026-07-01T09:00:00.000Z',
          'Try the same reading with an experimental model.',
        ),
        assistantLine(
          SESSION_IDS.yellowUnknownModel,
          cwd,
          '2026-07-01T09:00:05.000Z',
          'This entry reports a model id the adapter does not recognize.',
          MODELS.unknown,
          usage(2000, 3000, 44_500, 500), // total 50,000 → 25% of the estimated 200k default
        ),
      ],
    },
    {
      // Older session in ws-yellow: assistant entries carry NO usage → chars/4 fallback.
      workspaceName: 'ws-yellow',
      sessionId: SESSION_IDS.yellowNoUsage,
      lines: (cwd) => [
        userLine(
          SESSION_IDS.yellowNoUsage,
          cwd,
          '2026-07-01T10:00:00.000Z',
          'This session has no usage accounting at all, so the monitor has to fall back to estimation.',
        ),
        assistantLine(
          SESSION_IDS.yellowNoUsage,
          cwd,
          '2026-07-01T10:00:05.000Z',
          'Without a usage block the adapter reconstructs the conversation text and estimates tokens from character count.',
          MODELS.known,
          null,
        ),
        userLine(
          SESSION_IDS.yellowNoUsage,
          cwd,
          '2026-07-01T10:00:10.000Z',
          'Label that reading as an estimate wherever it is displayed.',
        ),
        assistantLine(
          SESSION_IDS.yellowNoUsage,
          cwd,
          '2026-07-01T10:00:15.000Z',
          'Every reading derived from inferred inputs is labeled estimated so the display stays honest.',
          MODELS.known,
          null,
        ),
      ],
    },
    {
      // Older session in ws-yellow: extended-context model id → 1M window, exact.
      workspaceName: 'ws-yellow',
      sessionId: SESSION_IDS.yellowBigWindow,
      lines: (cwd) => [
        userLine(
          SESSION_IDS.yellowBigWindow,
          cwd,
          '2026-07-01T11:00:00.000Z',
          'Run the reading against the extended context window variant.',
        ),
        assistantLine(
          SESSION_IDS.yellowBigWindow,
          cwd,
          '2026-07-01T11:00:05.000Z',
          'The extended context model resolves to a one million token window in the adapter map.',
          MODELS.bigWindow,
          usage(5000, 10_000, 233_000, 2000), // total 250,000 → 25% of 1M
        ),
      ],
    },
    {
      workspaceName: 'ws-orange',
      sessionId: SESSION_IDS.orange,
      lines: (cwd) => [
        userLine(
          SESSION_IDS.orange,
          cwd,
          '2026-07-02T18:20:00.000Z',
          'Keep iterating on the watcher wiring across the adapter seam.',
        ),
        assistantLine(
          SESSION_IDS.orange,
          cwd,
          '2026-07-02T18:20:05.000Z',
          'The watcher debounces change events and the polling fallback covers file systems without reliable events.',
          MODELS.known,
          usage(4400, 5200, 110_000, 900),
        ),
        userLine(
          SESSION_IDS.orange,
          cwd,
          '2026-07-02T18:20:10.000Z',
          'Fold the review notes into the session as well.',
        ),
        assistantLine(
          SESSION_IDS.orange,
          cwd,
          '2026-07-02T18:20:15.000Z',
          'Review notes are folded in; the session is carrying a heavier context footprint now.',
          MODELS.known,
          usage(5000, 6000, 124_000, 1000), // total 136,000 → 68% of 200k
        ),
      ],
    },
    {
      workspaceName: 'ws-red',
      sessionId: SESSION_IDS.red,
      lines: (cwd) => [
        userLine(
          SESSION_IDS.red,
          cwd,
          '2026-07-02T18:30:00.000Z',
          'Next step: wire the estimation fallback into the status command. TODO: handle the empty transcript case before release.',
        ),
        assistantLine(
          SESSION_IDS.red,
          cwd,
          '2026-07-02T18:30:05.000Z',
          'We decided to route every reading through the shared pipeline. Confirmed that the estimation fallback produces labeled readings.',
          MODELS.known,
          usage(3600, 6100, 141_000, 900),
        ),
        userLine(
          SESSION_IDS.red,
          cwd,
          '2026-07-02T18:30:10.000Z',
          'Should we cap the polling interval at ten seconds to keep the refresh guarantee?',
        ),
        assistantLine(
          SESSION_IDS.red,
          cwd,
          '2026-07-02T18:30:15.000Z',
          'The remaining task is to document the cap. Open question: should we surface the burn rate in the status line as well?',
          MODELS.known,
          usage(4000, 7000, 148_000, 1000), // total 160,000 → 80% of 200k
        ),
      ],
    },
    {
      workspaceName: 'ws-growing',
      sessionId: SESSION_IDS.growing,
      lines: (cwd) => [
        userLine(
          SESSION_IDS.growing,
          cwd,
          '2026-07-02T18:40:00.000Z',
          'Start a longer working session on the live view.',
        ),
        assistantLine(
          SESSION_IDS.growing,
          cwd,
          '2026-07-02T18:40:05.000Z',
          'Live view scaffolding is in place; the session will keep growing from here.',
          MODELS.known,
          usage(2500, 3500, 63_200, 800), // total 70,000 → 35% of 200k
        ),
      ],
    },
    {
      workspaceName: 'ws-empty',
      sessionId: SESSION_IDS.empty,
      lines: null, // zero-byte transcript: session exists, no reading producible
    },
    {
      workspaceName: 'ws-decisions',
      sessionId: SESSION_IDS.decisions,
      lines: (cwd) => [
        userLine(
          SESSION_IDS.decisions,
          cwd,
          '2026-07-02T18:50:00.000Z',
          'Which storage layout are we going with for saved artifacts?',
        ),
        assistantLine(
          SESSION_IDS.decisions,
          cwd,
          '2026-07-02T18:50:05.000Z',
          'We decided to use the adapter approach for session discovery, keeping agent-specific knowledge behind one seam.',
          MODELS.known,
          usage(1900, 2600, 44_900, 600),
        ),
        userLine(
          SESSION_IDS.decisions,
          cwd,
          '2026-07-02T18:50:10.000Z',
          'And what did the flaky refresh investigation conclude?',
        ),
        assistantLine(
          SESSION_IDS.decisions,
          cwd,
          '2026-07-02T18:50:15.000Z',
          'The root cause of the flaky refresh turns out to be the missing debounce, so we agreed to keep the 500ms debounce in the watcher.',
          MODELS.known,
          usage(2000, 3000, 44_400, 600), // total 50,000 → 25% of 200k
        ),
      ],
    },
    {
      workspaceName: 'ws-no-matches',
      sessionId: SESSION_IDS.noMatches,
      // Deliberately bland: no heuristic trigger phrases, no question marks.
      lines: (cwd) => [
        userLine(
          SESSION_IDS.noMatches,
          cwd,
          '2026-07-02T18:55:00.000Z',
          'Give me a plain tour of the repository layout.',
        ),
        assistantLine(
          SESSION_IDS.noMatches,
          cwd,
          '2026-07-02T18:55:05.000Z',
          'The source tree has a core directory, an adapters directory, and a cli directory. Shared utilities live under lib.',
          MODELS.known,
          usage(1400, 1900, 26_400, 300), // total 30,000 → 15% of 200k
        ),
      ],
    },
    {
      workspaceName: 'ws-bad-config',
      sessionId: SESSION_IDS.badConfig,
      lines: (cwd) => [
        userLine(
          SESSION_IDS.badConfig,
          cwd,
          '2026-07-02T18:58:00.000Z',
          'Read the session even though the workspace configuration file is broken.',
        ),
        assistantLine(
          SESSION_IDS.badConfig,
          cwd,
          '2026-07-02T18:58:05.000Z',
          'The monitor keeps running on default thresholds and names the configuration violation on stderr.',
          MODELS.known,
          usage(3000, 4000, 82_200, 800), // total 90,000 → 45% of 200k
        ),
      ],
    },
  ];
}

/** Growth turns replayed by scripts/fixtures/append-turns.sh (newest timestamps). */
function buildGrowthTurns(): Record<string, (cwd: string) => string[]> {
  return {
    // 35% → 38% → 39.5% → 68%: the final turn jumps across the 40% and 60%
    // boundaries in a single reading (multi-band collapse, FR-005).
    'ws-growing': (cwd) => [
      userLine(
        SESSION_IDS.growing,
        cwd,
        '2026-07-02T19:00:00.000Z',
        'Continue implementing the watcher module.',
      ),
      assistantLine(
        SESSION_IDS.growing,
        cwd,
        '2026-07-02T19:00:05.000Z',
        'Watcher module continued; debounce handling refined.',
        MODELS.known,
        usage(2700, 3800, 68_700, 800), // total 76,000 → 38%
      ),
      userLine(
        SESSION_IDS.growing,
        cwd,
        '2026-07-02T19:00:10.000Z',
        'Now add the polling fallback branch.',
      ),
      assistantLine(
        SESSION_IDS.growing,
        cwd,
        '2026-07-02T19:00:15.000Z',
        'Polling fallback branch added behind the subscription seam.',
        MODELS.known,
        usage(2800, 3900, 71_500, 800), // total 79,000 → 39.5%
      ),
      userLine(
        SESSION_IDS.growing,
        cwd,
        '2026-07-02T19:00:20.000Z',
        'Paste in the full review transcript and reconcile it with the notes.',
      ),
      assistantLine(
        SESSION_IDS.growing,
        cwd,
        '2026-07-02T19:00:25.000Z',
        'Review transcript reconciled; the session context grew sharply in this turn.',
        MODELS.known,
        usage(5000, 6000, 124_000, 1000), // total 136,000 → 68% (green → orange jump)
      ),
    ],
    // 25% → 68%: single jump into orange with fresh decision phrases (FR-015).
    'ws-decisions': (cwd) => [
      userLine(
        SESSION_IDS.decisions,
        cwd,
        '2026-07-02T19:10:00.000Z',
        'Bring in the whole design discussion so we can settle the remaining points.',
      ),
      assistantLine(
        SESSION_IDS.decisions,
        cwd,
        '2026-07-02T19:10:05.000Z',
        'We decided to keep the scanner a pure function, and we agreed to persist dismissals in the state file only.',
        MODELS.known,
        usage(5200, 6300, 123_500, 1000), // total 136,000 → 68% (green → orange jump)
      ),
    ],
  };
}

/**
 * (Re)generate every fixture deterministically. Existing generated trees are replaced
 * so replayed growth turns never leak into the next test run.
 */
export function generateFixtures(repoRoot: string = fixtureRepoRoot()): void {
  uuidCounter = 0;
  const fixturesDir = join(repoRoot, 'tests', 'fixtures');
  const projectsDir = join(fixturesDir, 'claude', 'projects');
  const growthDir = join(fixturesDir, 'growth');

  rmSync(projectsDir, { recursive: true, force: true });
  rmSync(growthDir, { recursive: true, force: true });
  mkdirSync(projectsDir, { recursive: true });
  mkdirSync(growthDir, { recursive: true });

  const workspaceNames = [
    'ws-green',
    'ws-yellow',
    'ws-orange',
    'ws-red',
    'ws-growing',
    'ws-empty',
    'ws-decisions',
    'ws-no-matches',
    'ws-bad-config',
  ];
  for (const name of workspaceNames) {
    const wsDir = join(fixturesDir, name);
    mkdirSync(wsDir, { recursive: true });
    writeFileSync(join(wsDir, '.gitkeep'), '');
  }

  // ws-bad-config: orange (60) below yellow (65) — ordering violation (FR-003).
  writeFileSync(
    join(fixturesDir, 'ws-bad-config', 'baton.config.json'),
    `${JSON.stringify({ thresholds: { yellow: 65, orange: 60, red: 75 } }, null, 2)}\n`,
  );

  for (const spec of buildTranscripts()) {
    const wsPath = join(fixturesDir, spec.workspaceName);
    const encoded = encodeWorkspacePathForFixtures(wsPath);
    const sessionDir = join(projectsDir, encoded);
    mkdirSync(sessionDir, { recursive: true });
    const transcriptPath = join(sessionDir, `${spec.sessionId}.jsonl`);
    const content = spec.lines === null ? '' : `${spec.lines(wsPath).join('\n')}\n`;
    writeFileSync(transcriptPath, content);
    // Pristine copy for append-turns.sh reset, for the replayable fixtures.
    if (spec.workspaceName === 'ws-growing' || spec.workspaceName === 'ws-decisions') {
      writeFileSync(join(growthDir, `${spec.workspaceName}.base.jsonl`), content);
    }
  }

  for (const [workspaceName, build] of Object.entries(buildGrowthTurns())) {
    const wsPath = join(fixturesDir, workspaceName);
    writeFileSync(
      join(growthDir, `${workspaceName}.turns.jsonl`),
      `${build(wsPath).join('\n')}\n`,
    );
  }
}

// CLI entry: `npx tsx scripts/fixtures/generate-fixtures.ts`
if (process.argv[1] !== undefined) {
  const invoked = resolve(process.argv[1]);
  const self = fileURLToPath(import.meta.url);
  if (invoked === self) {
    generateFixtures();
    console.error(`fixtures generated under ${join(fixtureRepoRoot(), 'tests', 'fixtures')}`);
  }
}
