// T055 — Estimation accuracy (SC-007): estimated readings fall within 10
// percentage points of the exact value for at least 95% of samples.
//
// The calibration corpus lives in tests/fixtures/calibration/ (generated by
// scripts/fixtures/generate-calibration.ts): transcripts whose assistant turns
// carry EXACT `message.usage` truth values over mixed content (prose, code,
// JSON). The truth was stamped at fixture-generation time with a real BPE
// tokenizer (gpt-tokenizer, cl100k_base) — NOT chars/DIVISOR — so this test
// runs tokenizer-free: it exercises the real runtime estimation path
// (readUsage over a usage-stripped copy of each transcript) and compares
// against the stamped truth.
//
// The acceptance criterion is SC-007 verbatim and must never be weakened; if
// it fails, the DIVISOR constant in src/lib/estimate.ts is what gets
// calibrated (T014/T055).
import { mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { afterAll, beforeAll, describe, expect, it } from 'vitest';
import { readTranscriptLines, readUsage, usageTotalOf } from '../../src/adapters/claude-code/transcript.js';
import type { SessionRef } from '../../src/core/monitor/types.js';

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
const calibrationDir = join(repoRoot, 'tests', 'fixtures', 'calibration');

/** SC-007 verbatim — do not weaken. */
const MAX_DIFF_PCT_POINTS = 10;
const MIN_PASS_FRACTION = 0.95;

interface ManifestSample {
  id: string;
  file: string;
  sessionId: string;
  contextWindow: number;
  exactTokens: number;
  exactPct: number;
  chars: number;
}

interface Manifest {
  truthTokenizer: string;
  samples: ManifestSample[];
}

let manifest: Manifest;
let scratchRoot: string;

beforeAll(() => {
  const manifestPath = join(calibrationDir, 'manifest.json');
  try {
    manifest = JSON.parse(readFileSync(manifestPath, 'utf8')) as Manifest;
  } catch {
    throw new Error(
      `missing calibration corpus at ${manifestPath} — run: npx tsx scripts/fixtures/generate-calibration.ts`,
    );
  }
  scratchRoot = mkdtempSync(join(tmpdir(), 'baton-estimate-accuracy-'));
});

afterAll(() => {
  rmSync(scratchRoot, { recursive: true, force: true });
});

/** Copy of a transcript with every `message.usage` block removed. */
function stripUsage(raw: string): string {
  const lines = raw.split('\n').map((line) => {
    if (line.trim() === '') return line;
    const parsed = JSON.parse(line) as { message?: { usage?: unknown } };
    if (parsed.message !== undefined && 'usage' in parsed.message) {
      delete parsed.message.usage;
    }
    return JSON.stringify(parsed);
  });
  return lines.join('\n');
}

interface SampleResult {
  id: string;
  exactTokens: number;
  estimatedTokens: number;
  exactPct: number;
  estimatedPct: number;
  diff: number;
}

/** Run the REAL estimation path (readUsage fallback) on a usage-stripped copy. */
async function measureSample(sample: ManifestSample): Promise<SampleResult> {
  const raw = readFileSync(join(calibrationDir, sample.file), 'utf8');

  // Ground truth from the transcript itself: last assistant usage total.
  const { entries } = readTranscriptLines(raw);
  let exactTokens: number | null = null;
  for (const { value } of entries) {
    const total = usageTotalOf(value);
    if (total !== null) exactTokens = total;
  }
  if (exactTokens === null) throw new Error(`${sample.id}: fixture carries no usage truth`);
  expect(exactTokens, `${sample.id}: manifest/fixture drift`).toBe(sample.exactTokens);

  // Isolated session-data layout holding the stripped copy.
  const claudeDir = join(scratchRoot, sample.id, 'claude');
  const workspace = join(scratchRoot, sample.id, 'ws');
  mkdirSync(workspace, { recursive: true });
  const projectDir = join(claudeDir, 'projects', workspace.replaceAll('/', '-'));
  mkdirSync(projectDir, { recursive: true });
  writeFileSync(join(projectDir, `${sample.sessionId}.jsonl`), stripUsage(raw));

  const session: SessionRef = {
    id: sample.sessionId,
    workspace,
    modelId: null,
    lastActivityAt: '2026-07-02T18:00:00.000Z',
  };
  const reading = await readUsage(session, { claudeDir });
  if (!('tokensUsed' in reading)) {
    throw new Error(`${sample.id}: estimation path produced no reading (${reading.reason})`);
  }
  expect(reading.precision).toBe('estimated'); // FR-013: inferred inputs stay labeled

  const estimatedPct = (reading.tokensUsed / sample.contextWindow) * 100;
  const exactPct = (exactTokens / sample.contextWindow) * 100;
  return {
    id: sample.id,
    exactTokens,
    estimatedTokens: reading.tokensUsed,
    exactPct,
    estimatedPct,
    diff: Math.abs(estimatedPct - exactPct),
  };
}

describe('estimation accuracy against tokenizer-stamped truth (SC-007)', () => {
  it('corpus is real: ≥30 mixed samples spanning a wide usage range, truth not chars/4', () => {
    expect(manifest.truthTokenizer).toContain('gpt-tokenizer');
    expect(manifest.samples.length).toBeGreaterThanOrEqual(30);
    const pcts = manifest.samples.map((sample) => sample.exactPct);
    expect(Math.max(...pcts) - Math.min(...pcts)).toBeGreaterThanOrEqual(60); // 20–90% spread
    // The stamped truth must NOT be the estimator's own output in disguise.
    const differing = manifest.samples.filter(
      (sample) => sample.exactTokens !== Math.ceil(sample.chars / 4),
    );
    expect(differing.length / manifest.samples.length).toBeGreaterThanOrEqual(0.9);
  });

  it(
    'estimated usage falls within 10 percentage points of exact for ≥95% of samples',
    { timeout: 60_000 },
    async () => {
      const results: SampleResult[] = [];
      for (const sample of manifest.samples) {
        results.push(await measureSample(sample));
      }

      const within = results.filter((result) => result.diff <= MAX_DIFF_PCT_POINTS);
      const failing = results
        .filter((result) => result.diff > MAX_DIFF_PCT_POINTS)
        .map((result) => `${result.id}: ${result.diff.toFixed(2)} pts`)
        .join(', ');
      expect(
        within.length / results.length,
        `samples beyond ${String(MAX_DIFF_PCT_POINTS)} points: ${failing === '' ? 'none' : failing}`,
      ).toBeGreaterThanOrEqual(MIN_PASS_FRACTION);
    },
  );
});
